# Generated by Django 3.2.12 on 2022-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphones', '0003_alter_reviews_price_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='frequency',
            field=models.TextField(default='0 Hz - 0 KHz'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='impedance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='headphone',
            name='sensitivity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
